### ISSUE TITLE
Cannot load file via .emacs

### ISSUE THREAD

**Issue by Louis-Cypher** [gizmomogwai/org-kanban#1]
I tried to automatically load your marvellous peace of software with:

> (with-eval-after-load 'dash
  (load "org-kanban"))

But sadly that doesn't work. If I load it (at the end of .emacs without the with-eval-statement I get an error indicating that dash is missing) 

Would you mind adding a solution for installation to the readme? Or even better providing your software via repository?

Thanks in advance,

Markus

**Comment by gizmomogwai** [comment]
Thanks for your kind words.
I personally use el-get. I guess I can easily come up with a recipe for that.
I think you refer to the default elpa repository, or would melpa or marmalada also be acceptable?

I use this on top of my emacs setup has to include more packages as the caskfile shows.
https://github.com/gizmomogwai/org-kanban/blob/master/Cask

**Comment by Louis-Cypher** [comment]
Great Software, kind words ;-) 

A recipe would be great. Melpa would be perfect. I already loaded org-brain from there. I'll have a look at el-get soon.

**Comment by gizmomogwai** [comment]
will try to do melpa .. looks a little bit easier than elpa :)

**Comment by gizmomogwai** [comment]
I already added an el-get rcp file. But will continue to look into melpa.

**Comment by gizmomogwai** [comment]
i created a pull request on melpa for a org-kanban recipe, along with fixing the autoloads for dash.
i will give you a notice here, as soon as the pull request goes through. then you should be able to test it!

**Comment by Louis-Cypher** [comment]
Great, thanks a lot! Looking forward to testing...

**Comment by gizmomogwai** [comment]
from the looks of it, it might take a while until i get into melpa...

**Comment by gizmomogwai** [comment]
i finally made it into melpa unstable :)
now you actually can install org-kanban with package-install :)

**Comment by gizmomogwai** [comment]
Please give it a try!

**Comment by Louis-Cypher** [comment]
Sorry that it took me that long to install. Installation worked like a charm after some initial hazzle with dash. Thanks a million times!

**Comment by gizmomogwai** [comment]
nice ... hope it is in sum more help than hazzle. thanks for the bugreport. it got me motivated to care for a melpa package :)
