### ISSUE TITLE
When nothing match it deletes the #+END:

### ISSUE THREAD

**Issue by bjonnh** [gizmomogwai/org-kanban#13]
Whenever I update a table with non existing tags it writes:
#+BEGIN: kanban :mirrored t :match "-archived&main"
|Archived|Canceled|Done|To_document|Current|Ready|Blocked|
|--|
nil
nil

and removes the #+END: tag.

**Comment by gizmomogwai** [comment]
thanks for this report as well.
for me it behaves different, but also not good :)
e.g. it produces same as you describe but keeps the #+END: tag.
still 

    |--|
    nil
    nil

does not read well!
