### ISSUE TITLE
can't create kanban board since version v0.4.10

### ISSUE THREAD

**Issue by veselinovic** [gizmomogwai/org-kanban#15]
After the update to v0.4.10 I got the following error:
```
Updating dynamic block ‘kanban’ at line 2...
org-kanban//cleanup-description: Symbol’s function definition is void: s-replace
```

switching back to version v0.4.9 and the errors are gone.

tested with a plain orgfile and one TODO-Entry.
Org mode version 9.2.2 (9.2.2-13-g0007df-elpa)

**Comment by gizmomogwai** [comment]
Thanks for the bug reports.
Looks like there is a problem with the dependencies specified for org-kanban. Especially "s" seems to be missing. Two options come to mind:
1. Get rid of the call to s-replace (its only at two places), 
2. Add the dependency.

May I ask which packaging system you are using?

Will try to do the first solution. Should be simple enough.

**Comment by gizmomogwai** [comment]
Should be fixed in 0.4.12.
I added s as dependency to the package header as well as to the el-get recipe.

**Comment by veselinovic** [comment]
@gizmomogwai sorry my late reply. The new version works again perfectly. To answer your questions (it might be of any value) I installed org-kanban with package-install and I had "s" installed as well. anyway thanks for the quick fix :+1: 

Cheers

**Comment by gizmomogwai** [comment]
@veselinovic lets see.
i found several not so nice things, but i hope those are cleaned up now.
