### ISSUE TITLE
org-kanban has problems with todos with | in them

### ISSUE THREAD

**Issue by gizmomogwai** [gizmomogwai/org-kanban#17]
e.g.
* TODO check ls | grep test

**Comment by gizmomogwai** [comment]
this is a tricky one, as org mode does not support proper escaping in links (especially not in links in tables).
i could replace the normal pipe symbol by e.g. https://www.compart.com/en/unicode/U+FF5C
for the links (it looks a little strange, depending on the font), but clicking the link is then broken (might not be the biggest problem).

**Comment by gizmomogwai** [comment]
funnily enough org mode replaces [] in descriptions of links with {} ... weird.

**Comment by gizmomogwai** [comment]
@cslux i have a solution for this now, by replacing normal pipes with U+FF5c and using custom_ids to link to the headings ... its a little ugly, because you have to have custom ids for the links to work, but i think thats the best i can do. would you be interested in this solution?

**Comment by cslux** [comment]
I would be interested in this solution. Thanks!
