### ISSUE TITLE
org-kanban/shift to support up/down

### ISSUE THREAD

**Issue by divansantana** [gizmomogwai/org-kanban#19]
I'm not sure if I missed it, but does org-kanban support moving tasks up/down in the various columns. This is nice to move the most NB things to the top to next get to them.

**Comment by gizmomogwai** [comment]
hi @divansantana,
no ... at the moment the only interaction is in changing the state of a todo item in the table.
i am sure this could be done, but changing the underlying org document in that way e.g. using `org-move-subtree-up` might have more severe side effects then i am currently up for :)
one of the problems might be, that the todos in the table are not necessarily on the same level, and then moving up down might not lead to unexpected behavior.
one could argue, that this is the "problem" of the user then ...

the next few weeks i do not have time to look into this, but in one, two months i could come back to this. i could look at a pull request though.

**Comment by divansantana** [comment]
Thanks @gizmomogwai . I couldn't help with a PR unfortunately.

I do understand the concern with this though. Still generally using graphical kanban boards, one could put the most nb items at the top to prioritize them. :thinking:

**Comment by gizmomogwai** [comment]
i still think the idea is very good ...
perhaps a "manual" solution would be interesting ... e.g. key to jump to the TODO, then use org modes mechanisms to change the prio (normally i think org-mode has also a prio (A-C by default)) or the order of the thing, and then a key to jump back and update the table. but thats not as natural as shift-up or something ... would also be cool to have either wasd or vim keybindings for that.

**Comment by divansantana** [comment]
@gizmomogwai If one could set a priority on the task and have the kanban board reflect that, that would be great!

**Comment by gizmomogwai** [comment]
ok .. if you have a chance, you can give the current version a try.
i added a subtree up/down to the `org-kanban/shift` command.
there is also `org-kanban/move-subtree-up` and `org-kanban/move-subtree-down`.
`org-kanban/shift` does not move by default anymore.
