### ISSUE TITLE
Feature request: Sort todos by their priorities.

### ISSUE THREAD

**Issue by dschaehi** [gizmomogwai/org-kanban#21]
Thanks for the cool package. I have a feature request: Would it be possible to provide a parameter that allows for sorting the todos in the table by their priorities (i.e., A, B, C)? At the moment the todos are sorted by the order of their appearances in the scope (from top to bottom).

**Comment by gizmomogwai** [comment]
thanks for the feature request ... i think this could be done ...
just need a little spare time ... just back from vacation, so there is a lot to do now :)

**Comment by dschaehi** [comment]
Thanks! It works well!

**Comment by kr63** [comment]
Christian,
I can't figure out how to sort my todos items based on their priorities.
Will you please to add a small example or create new asciinema with explanation?

**Comment by gizmomogwai** [comment]
HI @kr63 , please check out this table

    #+TODO: Todo Plan Develop Test Done
    * Todo [#A] Task One
    * Develop [#B] Two
    * Todo [#C] Three [0/2]
    #+BEGIN: kanban :mirrored t :layout ("..." . 1000) :scope nil :sort "P"
    | Done | Test | Develop | Plan | Todo        |
    |------+------+---------+------+-------------|
    |      |      |         |      | [[file:test2.org::*Three][Three {0/2}]] |
    |      |      | [[file:test2.org::*Two][Two]]     |      |             |
    |      |      |         |      | [[file:test2.org::*Task One][Task One]]    |
    #+END:

you can use org-kanban/configure-block to get a menu that tries to explain a little bit whats possible.
for sort you can use p and P for ascending/descending sorting by priority or o or O for sort by todo order.

hope this helps.

i agree, that the asciinemas are rather old now.
