### ISSUE TITLE
Cannot jump to the todos in the other file when :scope is used

### ISSUE THREAD

**Issue by dschaehi** [gizmomogwai/org-kanban#22]
It seems that when a todo is loaded from other file specified by the `:scope` parameter, then it is not possible to jump to the todo in the other file by using the corresponding link in the table. A proper link to the todo is needed using e.g. `file:<file name>::*Heading`

**Comment by gizmomogwai** [comment]
thanks for the bugreport ... will look into it, as soon as i am really back from vacation and have some spare time.

**Comment by gizmomogwai** [comment]
hi @dschaehi,
actually this is part of my manual testsuite and it works (at least for me).
I create a like like `[[file:test2.org::Heading][Heading]]` in the table. 
I am running emacs 26.2 and org mode 9.1.9.
reading the documentation it seems my link is indeed broken!
https://orgmode.org/manual/External-Links.html#FOOT29
my setting is:

    org-link-search-must-match-exact-headline is a variable defined in ‘org.el’.
    Its value is ‘query-to-create’

so it might work for me by chance.

**Comment by dschaehi** [comment]
Hi @gizmomogwai,

It seems that the links break when only one external file is present in the scope.
I see that there are two files in the scope in the following test file: https://github.com/gizmomogwai/org-kanban/blob/master/test1.org
Could you check whether the links break when there is only one external file in the scope (e.g., ":scope (test2.org))

**Comment by gizmomogwai** [comment]
thanks for the report ...
i was not expecting to have a org-kanban table in another file. 
there is was some special handling of scopes with only one file and so on.
now you should always get links with files in them if you use scope.

**Comment by dschaehi** [comment]
It works now. Thanks!
