### ISSUE TITLE
Support for tree depth

### ISSUE THREAD

**Issue by namdnguyen** [gizmomogwai/org-kanban#23]
What do you think about supporting depth constraints in the configuration? `:depth 1` could be all first level entries, if `:scope` is not set to `tree`. If `:scope tree`, then it would be the highest level entries relative to the tree.

**Comment by gizmomogwai** [comment]
sounds interesting. do you know the org-mode api? would it directly support something like this?
I am in vacation the next few weeks, so I will not be able to implement that for now.

**Comment by namdnguyen** [comment]
It's been a while since I worked with the org-mode APIs, but I do think that there are functions from the org-mode [Element API - Headlines](https://orgmode.org/worg/dev/org-element-api.html#org6e589e2) that can help. `org-element-at-point` retrieves `level`, which is the headline level in the file. Maybe it could be used as part of the function after mapping with `match` and `scope`.

Don't know if `level` is affected by `:scope tree` mapping, but seems like it might not and would require an additional step for determining relative depth within a tree.

**Comment by gizmomogwai** [comment]
Please have a look at version 0.4.24. I added :max-level 1 that should work as you wish.
I could i think also change this into a range.

**Comment by namdnguyen** [comment]
Hey @gizmomogwai, it works great for me! It fits my purposes with `max-level` as a single value, but I could see how someone would benefit from a range.

I had a little trouble at first with `:max-level: 1`, but then I figured out that the level is based on the document root level. My table is kept in a level 1 heading, so I needed `:max-level: 2`. 

I also use `:scope: tree`, which worked as expected. I think that there might be a bug with `:scope nil`  and `:max-level`, though. I get a blank table when I know that there should be candidates.

**Comment by gizmomogwai** [comment]
Hi @namdnguyen thanks for testing.
I will push a new version soon, that renames max-level to depth. I hope this is not a problem.
about :scope nil: could you please try to strip down you example and create a new issue here?

**Comment by gizmomogwai** [comment]
Do you know org-kanban/configure-block? its a small ui to configure the org-kanban block.

**Comment by namdnguyen** [comment]
Yes, I usually use it to check the parameters, but I like to configure by hand afterwards.

**Comment by gizmomogwai** [comment]
perfect .. sure .. its much faster to edit directly
