### ISSUE TITLE
Allow more flexible sorting of org-table entries

### ISSUE THREAD

**Issue by gizmomogwai** [gizmomogwai/org-kanban#25]
sort by state
sort by prio
and all combinations of them ascending and descending.
i propose s for state and p for prio followed by < (ascending) or > (descending).

e.g. s<p>

**Comment by namdnguyen** [comment]
Another alternative you could do is to follow the convention that the `org-sort` function uses to sort sub-headings. This would also allow you to have the keys mapped for any new parameters that you would wanted to add.

From the `org-sort-entries` doc string:

```
a   Alphabetically, ignoring the TODO keyword and the priority, if any.
c   By creation time, which is assumed to be the first inactive time stamp
    at the beginning of a line.
d   By deadline date/time.
k   By clocking time.
n   Numerically, by converting the beginning of the entry/item to a number.
o   By order of TODO keywords.
p   By priority according to the cookie.
r   By the value of a property.
s   By scheduled date/time.
t   By date/time, either the first active time stamp in the entry, or, if
    none exist, by the first inactive one.

Capital letters will reverse the sort order.
```

So for the example mentioned in #24, sorting by ascending state and then ascending priority would be `op`. Descending state, then ascending priority would be `Op`

**Comment by namdnguyen** [comment]
This is how the `org-sort` prompt looks in emacs:

![image](https://user-images.githubusercontent.com/13385781/72910206-d075e080-3cfd-11ea-813c-61d1dbee5a01.png)

**Comment by gizmomogwai** [comment]
nice .. thanks for that ... not sure if i can reuse org's code or if i can implement all options, but would be good for sure.

**Comment by gizmomogwai** [comment]
i had a quick look at org-sort and its friends, but i do not see how to reuse it. but if i implement it i will keep at least the naming.

**Comment by gizmomogwai** [comment]
hi @namdnguyen ,
please have a look at the newest version.
it should be org-kanban/version 0.4.23. Melpa will hopefully update soon.
How do you install org-kanban btw.?

**Comment by namdnguyen** [comment]
Hi @gizmomogwai, it worked flawlessly for me. I install org-kanban with Melpa.
