### ISSUE TITLE
Warnings about org-table-* functions not known to be defined

### ISSUE THREAD

**Issue by omsai** [gizmomogwai/org-kanban#27]
It looks like an explicit `(require org-table)` is necessary to silence these warnings:

```
Jun 21 11:04:52 xm2 emacs[37291]: Contacting host: melpa.org:443
Jun 21 11:04:53 xm2 emacs[37291]: Generating autoloads for org-kanban.el...
Jun 21 11:04:53 xm2 emacs[37291]: Generating autoloads for org-kanban.el...done
Jun 21 11:04:53 xm2 emacs[37291]: Wrote /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951/org-kanban-autoloads.el
Jun 21 11:04:53 xm2 emacs[37291]: Wrote /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951/org-kanban-autoloads.el
Jun 21 11:04:53 xm2 emacs[37291]: Checking /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951...
Jun 21 11:04:53 xm2 emacs[37291]: Checking /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951...
Jun 21 11:04:53 xm2 emacs[37291]: Checking /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951...
Jun 21 11:04:53 xm2 emacs[37291]: org-kanban.el:241:1:Warning: Unused lexical variable ‘row-index’
Jun 21 11:04:53 xm2 emacs[37291]: In end of data:
Jun 21 11:04:53 xm2 emacs[37291]: org-kanban.el:1001:1:Warning: the following functions are not known to be defined:
Jun 21 11:04:53 xm2 emacs[37291]:     org-table-current-column, org-table-goto-line,
Jun 21 11:04:53 xm2 emacs[37291]:     org-table-get-field
Jun 21 11:04:53 xm2 emacs[37291]: Wrote /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951/org-kanban.elc
Jun 21 11:04:53 xm2 emacs[37291]: Checking /home/omsai/.emacs.d/elpa/org-kanban-20200601.1951...
Jun 21 11:04:53 xm2 emacs[37291]: Done (Total of 1 file compiled, 2 skipped)
```

I'm not familiar with elisp enough to fix the unused lexical variable row-index warning.  I'll create a PR for org-table.

**Comment by gizmomogwai** [comment]
what are the steps to reproduce that? looks like you are just installing from melpa and byte-compiling the package while installing?

**Comment by omsai** [comment]
The easiest way to reproduce is running flycheck: https://www.flycheck.org/en/latest/ ... you can see a list of those warnings with `M-x flycheck-list-errors`.  2 of the 3 warnings go away when adding `(require org-table)`.  That's how I originally noticed the warnings.  Indeed, showing the MELPA output was probably not the best way to demonstrate the problem.  If you haven't used flycheck before, it might be something you'll enjoy a lot.

**Comment by gizmomogwai** [comment]
ok ... i found the row-index thingy ... will publish a new version ...

about org-table i dont yet understand the problem. what version of emacs and org-mode do you use?
for emacs i have 26.3 for org-mode i have 9.1.9. perhaps the scope of the byte-compile is much smaller than when its run really in emacs (my understanding would be that org-table is autoloaded by org because i just can enter a table a soon as i am in org mode, but i could be wrong there... i will just add it now :) ).

**Comment by omsai** [comment]
I'm using org-mode 9.1.9 but with Emacs 26.1 on Debian :shrug:

**Comment by gizmomogwai** [comment]
thanks ... lets wait until org-kanban is populated on melpa ... and what errors you now get when installing :) thanks for the report anyways! the row-index thing i also saw already in flycheck, but was to lazy to fix.
