### ISSUE TITLE
Hide Keywords?

### ISSUE THREAD

**Issue by typkrft** [gizmomogwai/org-kanban#28]
I am trying to setup a kanban using only Keywords [ ] [-] [X], but am unsure how to. Also it seems that the links don't fit within the columns. 
<img width="1185" alt="Screen Shot 2020-09-12 at 1 46 28 PM" src="https://user-images.githubusercontent.com/12100960/93001643-644f2380-f4fe-11ea-8901-eafd39099607.png">

**Comment by gizmomogwai** [comment]
Hi, thats weird, could you share your original org file with the testdata?
I think your font makes up a for a lot of the problems. org-kanban did not implement the org-tables on its own, so i would suggest if you do org-tables with links in them and some special characters, you will get the same problems?!

**Comment by gizmomogwai** [comment]
the usage of unicode for the TODO keywords is superneat though!

**Comment by gizmomogwai** [comment]
alternatively could you disable only your special font settings for org-mode?

**Comment by gizmomogwai** [comment]
which unicode charachters are you using btw. i looked into ballot box * and check mark and some more, but did not find your nice set!

**Comment by typkrft** [comment]
Thanks, I'll try disabling some of my font settings to start with. 

Unicode Symbols are are supplied by [Nerd Font](https://github.com/ryanoasis/nerd-fonts) and Prettify Symbols replaces `[ ] [-] [X]` with       . It might be because I am not using monospaced fonts and the unicode characters have some weird spacing issues outside of the monospace font variants.

**Comment by gizmomogwai** [comment]
Any luck without the fancy fonts? Does it look better now?

**Comment by typkrft** [comment]
It seems to be something in my configuration. I'm not sure if it's prettify symbols mode or the fonts I'm using, but I tried it on a vanilla install of doom emacs and it seemed to work just fine I'll go ahead and close this and when I have time I'll look for the exact problem and update the thread. Thanks!
