### ISSUE TITLE
[FEATURE REQUEST] Support heading hierarchy not related to TODO keywords

### ISSUE THREAD

**Issue by wakatara** [gizmomogwai/org-kanban#29]
Really interesting project. I was wondering if it was possible to extend this beyond TODO keywords to the following.

For a set of arbitrary org-mode headings, render the table (and allow someone to move things between tables and have it change the structure in the underlying file) to yield something like this :

``` org-mode
** Idea

[[file:gtd-tools-shootout.org][GTD Tools Shootout]]
[[file:thinking-the-new-superpower.org][Thinking - the new superpower]]
[[file:how-to-hire-data-scientists.org][How to Hire Data Scientists]]
[[file:high-and-low-trust-cultures.org][High and Low Trust Cultures]]

** Draft

[[file:2002-reading-list-and-recommendations.org][2002 Reading List and Recommendations]]
[[file:software-tools-i-use-2021-edition.org][Software Tools I Use - 2021 Edition]]

** Edit

[[file:what-to-spend-money-on.org][What to Spend Money On]]

** Published

[[file:the-scil+r-bucket-system.org][The SCIL+R Bucket System]]
[[file:gtd-emacs-and-the-age-of-remote-collaboration.org][GTD, Emacs, and the age of remote collaboration]]
[[file:career-progression-and-discovery-framework.org][Career Progression and Discovery Framework]]
[[file:organizational-foundations-for-data-teams.org][Organizational Foundations for Data Teams]]

#+BEGIN: kanban :mirrored t
| Idea | Draft | Edit | Published |
|------+-------+------+-----------|

#+END:

```
(ok, yeah... so I was hoping this was how your code *actually* worked, so never hurts to ask how easy it would be to support that... =]  It seemed way more flexible.).

Lemme know if that's not clear what I'm after. Basically a kanban board for my blog queue (or any other queue I'm using that doesn't need to be tired to the TODO keywords hierarchy but is instead tired to the structural hierarchy of the org-mode document headings. (obviously just one level of structured headings).

thanks!
Daryl.

**Comment by gizmomogwai** [comment]
Hi Daryl,

from a first glance at your idea i think this will be very hard to translate to what org-kanban does at the moment.
your lists of things structured by headings, a are very "informally", meaning the org helper functions do not know much about it. even the lists of things in a heading are not a list, but just text with links in them.

i think doing it from scratch (without any org-mode support) would be simpler.

**Comment by wakatara** [comment]
Hmmm.. interesting. Would a hack to this be to create the `TODO` keywords I want as separate flow in the app (so, Idea, Draft, Edit, Published) and then org-kanban would pick them up? I'm trying to reverse hack as many of the features I like and found useful in experimenting briefly with Notion back into org-mode. 

If that would force org-kanban to pick up *all* keywords, is there a way we could modify org-kanban to have a directive where it controls the keywords it makes the board out of? 

lemme know (and merry Xmas is you celebrate!)

**Comment by gizmomogwai** [comment]
Mhh ... 
not sure that I understand all what you mean. "Notion" is another tool to manage tasks I guess?
In org mode every org file can have custom TODO keywords.

e.g. https://raw.githubusercontent.com/gizmomogwai/org-kanban/master/test2.org defines in the first line alternate keywords.

one also can have several sets of todo keywords e.g. 
    
    #+TODO: Todo Plan Develop Test | Done
    #+TODO: TODO PLAN DONE1 DONE2 | DONE3

org-kanban can then only make use of a subrange of those with the :range parameter on the table.
e.g. 


    #+TODO: TODO DONE
    #+TODO: Idea Draft Edit Published
    * TODO normal todo
    * DONE normal done
    * Idea one
    * Idea two
    * Idea three
    * Publish done1
    #+BEGIN: kanban :layout ("..." . 1000) :scope (test1.org test2.org) :range ("Idea" . "Published")
    #+END 
 
should give you something like you wish for. you still could use normal headings without keywords as a way to structure things further if required.

**Comment by wakatara** [comment]
Seriously, every time I think I am getting better at emacs I find out a new thing. I literally did not know about the ability to define the per file keywords. 

And yes, Notion is a web based (more writing and organizing tool) which had some nice features I was checking out for collab and a web-based workflow. It's lack of deep task management (though you can kinda fake it) made me lie some features that I figured I might want to steal for my emas setup. That's how org-kanban got involved... =] The kanban "database views" in Notion are very nice to work with and super handy.

This is helpful. Will experiment. Thanks!

**Comment by wakatara** [comment]
Actually, I just checked this out and it works pretty much as advertised on the tin. Thank you. I am sorry I missed the fact you could create your own `TODO` list per file. That makes a big difference. 

I am having a few table alignment artifacts due to the fact I have links in the TODOs. Is there any solution for that or is that something more to do with org-table.

Thanks very much for putting the time in to build this software. It's going to come in quite handy.

(also, I assume the fact each kanban entry is on a line rather than top aligned is related to how you implemented, yes? You create a line per item and then have that deal with the entire table column structure? - so impossible to top align entries for each column?).

**Comment by gizmomogwai** [comment]
About alignment ... there was a feature request I think for that, but changing the todo level would make that very unpredictable. perhaps if we could just do that without the manipulation feature, we could "squash" the table together to not take as many lines ... just to get a better overview.

**Comment by gizmomogwai** [comment]
actually with commit efd9b38ab4902ee2afe542d77c23a363c6f0e33c a flag :compressed is implemented that safes the vertical space like you wish for ... this is more of a overview feature, as directly interacting with the tasks is not straight forward anymore
