### ISSUE TITLE
Feature request: function to initialize the kanban

### ISSUE THREAD

**Issue by Trevoke** [gizmomogwai/org-kanban#3]
Sure, we can do the custom block and C-c ourselves but:

`M-x org-kanban-initialize` can add a kanban at the top of the file and `C-u M-x org-kanban-initialize` can add a kanban at the bottom of the file.
Basically, I imagine:

1. save-excursion
2. goto min or goto max
3. insert block in buffer
4. move point inside block
5. call the function behind `C-c`

Boom!

**Comment by gizmomogwai** [comment]
Will for sure do, today I am not so much at the computer, but will try to get to it tomorrow.

**Comment by gizmomogwai** [comment]
Please check out org-kanban/initialize ...
Its always inserting at the current point, but a simple expand region, cut, move to where you want to have it, paste should fix this ...
