### ISSUE TITLE
Feature Request: Filter workflow states from the Kanban view

### ISSUE THREAD

**Issue by e0d** [gizmomogwai/org-kanban#32]
I'd like to be able to filter arbitrary workflow states from a kanban board.

For example, I'd like to be able to ignore things in the abandoned state or the ice-box state.

Let me know if such a feature sounds possible and interesting.

**Comment by gizmomogwai** [comment]
At the moment there is already the range parameter. 
If you would put abandoned and ice-box to the end of the states, then you could select everything needed with `:range ("Todo" . "Done")` if you would have e.g. the header `#+TODO: Todo Plan Develop Test | Done Iced Abandoned`

**Comment by edwinclement08** [comment]
Thanks @gizmomogwai, this was exactly what I wanted.
