### ISSUE TITLE
Links to files in subdirectories do not work

### ISSUE THREAD

**Issue by thvoigtmann** [gizmomogwai/org-kanban#33]
I noticed that links from the kanban table to files in subdirectories do not work. I have a bunch of org files for individual projects that are organized in subdirectories to a common `org-directory`, where I have a master file with several kanban tables using something like `kanban: scope(projects/first.org)`.

I think the reason is that the code to create links uses `current-buffer` converted to a string as the file name, which only works if all files are in the same directory.

I don't know enough about the code yet, but the following appears to work in my case:
```lisp
(defun org-kanban//link-for-custom-id (custom-id file description)
  "Create a link for CUSTOM-ID, optionally USE-FILE FILE and DESCRIPTION."
  (if custom-id
    (format "[[file:%s::#%s][%s]]" (file-relative-name (buffer-file-name file) org-directory) custom-id description)
    nil))
(defun org-kanban//link-for-heading (heading file description)
  "Create a link for a HEADING optionally USE-FILE a FILE and DESCRIPTION."
  (if heading
      (format "[[file:%s::*%s][%s]]" (file-relative-name (buffer-file-name file) org-directory) heading description)
    (error "Illegal state")))
```
where `org-directory` is the base path of the org files that I keep. (In principle, just `(buffer-file-name file)` instead of `file` would do I guess.)

**Comment by gizmomogwai** [comment]
Thanks for the bugreport. This is indeed a scenario that I never looked at. On a first glance your solution does not break anything, besides putting absolute filepaths into the table. (without the file-relative-name to org-directory).
Best would be possibly to make the link relative to the file that defines the table though.

**Comment by gizmomogwai** [comment]
Some experimenting showed, that
```
(file-relative-name (buffer-file-name file) (file-name-directory (buffer-file-name (current-buffer))))
```
gives a nice relative name, at least fo the subfolder usecase.

**Comment by thvoigtmann** [comment]
Thank you for the fast reply! I confirm your solution works for me.
