### ISSUE TITLE
Feature Request: org-kanban/initialize-at-heading

### ISSUE THREAD

**Issue by fleimgruber** [gizmomogwai/org-kanban#36]
`org-kanban/initialize-at-heading` (or similar) would put the kanban table at the end of the current top-level heading (maybe also inserting a second-level heading with the title "kanban" or similar). This would support the usage of an Org mode file that contains projects as top level headings and a user wanting to have a kanban board for each project. Is there an obvious way of doing this already that I am missing?

**Comment by gizmomogwai** [comment]
At the moment there are only the functions `org-kanban/initialize-at-beginning`, `at-end` and `here` available.
Do you know of a function that inserts an arbitrary code snippet in a way that you would like into an org buffer? If so, this could be used with a minimal org-kanban that then could be configured. 
Would probably be best to restrict the org-kanban in this case to the current tree.

**Comment by gizmomogwai** [comment]
you can give the option `:scope tree`a shot .. that should already be in place!
