### ISSUE TITLE
feature: layout: add link-cut-prefix-length for kanban on diary contexts?

### ISSUE THREAD

**Issue by pedro-nonfree** [gizmomogwai/org-kanban#46]
Today I tried to put a kanban in my daily-diary notes, my daily-diary notes all start with a orgmode timestamp

So it looks like this

(I removed the links and properties of the nodes to make it simpler to follow)

```orgmode
* 2024
** w28
*** [2024-07-13 Sat] [0/3]

#+BEGIN: kanban :layout ("$" . 14) :scope tree
| WISH           | TICKLER | NEXT | PLANNED | HOLD | DOING | VERIFY | EXPLAIN | CLOSED | DONE |
|----------------+---------+------+---------+------+-------+--------+---------+--------+------|
| {2024-07-13 S$ |         |      |         |      |       |        |         |        |      |
| {2024-07-13 S$ |         |      |         |      |       |        |         |        |      |
| {2024-07-13 S$ |         |      |         |      |       |        |         |        |      |
#+END:

**** WISH [2024-07-13 Sat 11:00] one topic
**** WISH [2024-07-13 Sat 12:20] another one
**** WISH [2024-07-13 Sat 13:10] third topic
```

The nice thing about this, is that the headings can get easily sorted around the day (with `(org-sort)`), and also, it is highlighted, always uses same length, etc. So I have some functions that discard this initial part when necessary

In that case, I would need, and maybe is useful for others, a way to cut a number of characters as a prefix, according to `(length "[2024-07-13 Sat 11:00]")` that would be 22 chars, because, that way, as you see, is not very useful

I would like to look this way:

```
* 2024
** w28
*** [2024-07-13 Sat] [0/3]

#+BEGIN: kanban :layout ("$" . 14) :prefix-cut 22 :scope tree
| WISH        | TICKLER | NEXT | PLANNED | HOLD | DOING | VERIFY | EXPLAIN | CLOSED | DONE |
|-------------+---------+------+---------+------+-------+--------+---------+--------+------|
| one topic   |         |      |         |      |       |        |         |        |      |
| another one |         |      |         |      |       |        |         |        |      |
| third topic |         |      |         |      |       |        |         |        |      |
#+END:

**** WISH [2024-07-13 Sat 11:00] one topic
**** WISH [2024-07-13 Sat 12:20] another one
**** WISH [2024-07-13 Sat 13:10] third topic
```

Thank you very much for your attention

**Comment by gizmomogwai** [comment]
thanks for the feature request.
it is quite reasonable (and should not be too hard to implement), BUT I do not know at the moment the best ui for it.
Also (on first thought, which is not always the best) I would not like to add another parameter, but perhaps make the existing layout parameter more flexibel (or even rename it to `:transform`). Let me see if I can come up with something usefule.

**Comment by gizmomogwai** [comment]
I just checked the source and luckily this is already implemented, but not nicely documented.
Useing e.g. the fantastic magnars/s.el library you could write something like `:layout (lambda (s) (s-truncate 10 (s-chop-left 5 s) "$"))`. this removes the first 10 letters and then makes the rest of the string maximum 10 characters long (including the `$` in this case.

It has its quirks, if the heading is not long enough, but for your case this should be ok, as you can guarantee that all headings have at least the timestamp at the front.

Please let me know if that works for you. Will close this for now (even if the documentation and editor do not support this feature).

**Comment by pedro-nonfree** [comment]
sorry the late response, so good that works

Inspired by something I use also for the agenda views [1], I did something like:

```lisp
(defun my/no-ts (s)
  "remove timestamps"
  (replace-regexp-in-string "\\[[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}[^]]*\\]" "" s))
```

that way, it is rendered like this (I like the space because is one character that notes that had a removed timestamp):

```
#+BEGIN: kanban :layout my/no-its :scope tree
| WISH   | TICK | NEXT | PLAN | HOLD | DOIN | ¿OK? | SAVE | QUIT | DONE |
|--------+------+------+------+------+------+------+------+------+------|
| [[file:board.org::#test1][ test1]] |      |      |      |      |      |      |      |      |      |
| [[file:board.org::#test2][ test2]] |      |      |      |      |      |      |      |      |      |
| [[file:board.org::#test3][ test3]] |      |      |      |      |      |      |      |      |      |
| [[file:board.org::#test3][test4]]  |      |      |      |      |      |      |      |      |      |
#+END

*** WISH [2025-01-08 Wed 02:53] test1
:PROPERTIES:
:CUSTOM_ID: test1
:END:
:TRACE:
- State "WISH"       from              [2025-01-08 Wed 02:53]
:END:
*** WISH [2025-01-08 Wed 02:53] test2
:PROPERTIES:
:CUSTOM_ID: test2
:END:
:TRACE:
- State "WISH"       from              [2025-01-08 Wed 02:53]
:END:
*** WISH [2025-01-08 Wed 02:53] test3
:PROPERTIES:
:CUSTOM_ID: test3
:END:
:TRACE:
- State "WISH"       from              [2025-01-08 Wed 02:53]
:END:
*** WISH test4
:PROPERTIES:
:CUSTOM_ID: test3
:END:
:TRACE:
- State "WISH"       from              [2025-01-08 Wed 02:54]
:END:
:PROPERTIES:
:CREATED:  [2025-01-08 Wed 02:54]
:CUSTOM_ID: board_180
:END:
```

rendered as

![image](https://github.com/user-attachments/assets/32197a1a-640f-4471-a593-7f560d3b80cb)

so yes, very happy

[1]

```lisp
(defun my/org-agenda-hide-inactive-timestamps ()
  "Hide inactive timestamps (like [2024-12-28 Sat]) from agenda entries."
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "\\[[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}[^]]*\\]" nil t)
      (replace-match "" nil nil))))

(add-hook 'org-agenda-finalize-hook #'my/org-agenda-hide-inactive-timestamps)
```

**Comment by gizmomogwai** [comment]
amazing .. i like how you make use of normal emacs mode hooks to achieve that :)
