### ISSUE TITLE
Feature request: allow a "mirrored" kanban mode

### ISSUE THREAD

**Issue by Trevoke** [gizmomogwai/org-kanban#5]
As in https://theagileist.wordpress.com/tag/mirrored-kanban-board/

basically, "todo" is on the right and "done" is on the left, which is more natural to  Europeans: since we tend to look at things from left to right, our eyes will naturally fall first on what's in closest to being done.

**Comment by gizmomogwai** [comment]
nice idea ... thanks .. i never heard of mirrored kanban, but it kind of makes sense.
will have a look.

**Comment by gizmomogwai** [comment]
i really like the idea .. i would suggest to make this the default
to disable it

````
#+BEGIN: org-kanban :mirror nil
````

**Comment by Trevoke** [comment]
I think that's a good idea. It might be worth adding a link explaining it in the README - I think most people who know Kanban just know it as left to right, so they would wonder.
