### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by Wheest** [gizmomogwai/org-kanban#8]
Hi there, I've been exporting orgfiles with Kanban tables to HTML, and have found that the internal links on the table are broken in the export.  

Looking at the code, it seems like this is becuase the links are stored in the `(format "[[file:%s::%s][%s]]" file heading description)) ""))` format.  Is there support to store links in the table using the heading's `:ID:` or `:CUSTOM_ID:` property?

**Comment by gizmomogwai** [comment]
Hi @Wheest, sorry I am in vacation right now.
The addition of the links was a recent experiment to allow org-kanban tables to be made up from several org-files.
I am no expert in org-mode so I am not sure, how you can specify links otherwise. Can you come up with a format that works cross files and exports to html? I guess thats pretty hard, because the export would only export one file.

That being said, I could look into an option for the org-kanban tables, that make use of e.g. local links only, which should then work for the html export (I think that is, what I had before). How does this sound?

**Comment by gizmomogwai** [comment]
Mhh ... on a second thought, this might also be a problem of org-export.
If org-mode exports something, all links supported by org-mode should be exported in a meaningful way, right?
I still will try to implement something as described above.

**Comment by Wheest** [comment]
Yes, I believe that HTML export isn't consistent when it uses headline name links.  My export had the Kanban table in the same org file as the headline and even then it didn't link properly.  That's a weakness of org-export ofc, but UIDs can mitigate the issue.

There's the function `(org-id-store-link)` which generates a hash-like unique id for a headline, putting it in the property drawers like this:

```
* My headline
:PROPERTIES:
:ID:       553f6539-29af-403a-b474-59e131b0224b
:END:
```
Then when you create a link, use the format `[[id:553f6539-29af-403a-b474-59e131b0224b][My Link Name]]`.  Custom-id is for when you want to give your headline a more meaningful UID. 

When I want to create a UID for a headline and copy it to the clipboard, I have the binding `("C-c l" . (lambda () (interactive) (org-id-store-link) (org-id-copy)))`.

**Comment by Wheest** [comment]
There's the [org-property API](https://orgmode.org/manual/Using-the-property-API.html) which defines some standard functions for getting and setting properties.

**Comment by gizmomogwai** [comment]
Thanks for these examples, will try to add the is thing as well (I can push for your testing the custom_id solution already). Could you pull directly from master and test if it works for you?

**Comment by gizmomogwai** [comment]
@Wheest could you please try out if the current master is better suited for you?
it only implements the thing with custom_id at the moment.
if that works for you, i will also add id support.

**Comment by Wheest** [comment]
This works great, thanks!  The Kanban links in my HTML export work without a hitch.  `id` is a nice feature which would catch any times that I forget to create a `custom_id`, however I'm not sure if that would break anyone's workflow, since the preference would be `custom_id` -> `id`,  with no headlines.

**Comment by gizmomogwai** [comment]
one question about the id's (not custom id's) ... org-id-store-link creates by default a random uuid and stores it in the properties. if you do not add this by hand or script, there is no way to reference an org-entry by id, right? so you have to either create a custom id or and id (kind of manually)?

**Comment by Wheest** [comment]
yeah, as far as I'm aware id's are generated deterministically according to some scheme, and stored in some lookup table somewhere (this is my intuition rather than backed up by code).  So the only way to reference an org headline by id is to create one for it. 

There are commands:
- `org-id-get-create` - `(org-id-get-create &optional FORCE)`
Create an ID for the current entry and return it.
If the entry already has an ID, just return it.
With optional argument FORCE, force the creation of a new ID.
- `(org-id-store-link)` - Store a link to the current entry, using its ID.

There are also a lot of org-id related functions, however my lisp is a bit rusty

**Comment by gizmomogwai** [comment]
i think its created randomly (at least for me). e.g. i run two times org-id-store-link on the same entry (after the first run, i delete again the added property).

**Comment by gizmomogwai** [comment]
Please have a look now. Supported are now custom_ids, ids and headings ...
in file links are created, if the org-kanban table is in the same file as the entry linked to.
i think this should be good for your html exports!
